// <auto-generated />
using System;
using CongestionTaxCalculator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongestionTaxCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(CongestionTaxDbContext))]
    partial class CongestionTaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsJulyTollFree")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDailyFee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SingleChargeIntervalMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsJulyTollFree = true,
                            MaxDailyFee = 60,
                            Name = "Gothenburg",
                            SingleChargeIntervalMinutes = 60
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollFeeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("Fee")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TollFeeSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            EndTime = new TimeOnly(6, 29, 0),
                            Fee = 8,
                            StartTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            EndTime = new TimeOnly(6, 59, 0),
                            Fee = 13,
                            StartTime = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            EndTime = new TimeOnly(7, 59, 0),
                            Fee = 18,
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            EndTime = new TimeOnly(8, 29, 0),
                            Fee = 13,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            EndTime = new TimeOnly(14, 59, 0),
                            Fee = 8,
                            StartTime = new TimeOnly(8, 30, 0)
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            EndTime = new TimeOnly(15, 29, 0),
                            Fee = 13,
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            EndTime = new TimeOnly(16, 59, 0),
                            Fee = 18,
                            StartTime = new TimeOnly(15, 30, 0)
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            EndTime = new TimeOnly(17, 59, 0),
                            Fee = 13,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CityId = 1,
                            EndTime = new TimeOnly(18, 29, 0),
                            Fee = 8,
                            StartTime = new TimeOnly(18, 0, 0)
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollFreeDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDayBeforeHoliday")
                        .HasColumnType("bit");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("TollFreeDates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Day = 1,
                            Description = "New Year's Day",
                            IsDayBeforeHoliday = false,
                            Month = 1,
                            Year = 2013
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Day = 28,
                            Description = "Maundy Thursday",
                            IsDayBeforeHoliday = false,
                            Month = 3,
                            Year = 2013
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Day = 29,
                            Description = "Good Friday",
                            IsDayBeforeHoliday = false,
                            Month = 3,
                            Year = 2013
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Day = 1,
                            Description = "Easter Monday",
                            IsDayBeforeHoliday = false,
                            Month = 4,
                            Year = 2013
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Day = 30,
                            Description = "Day before May 1st",
                            IsDayBeforeHoliday = false,
                            Month = 4,
                            Year = 2013
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            Day = 1,
                            Description = "May Day",
                            IsDayBeforeHoliday = false,
                            Month = 5,
                            Year = 2013
                        },
                        new
                        {
                            Id = 7,
                            CityId = 1,
                            Day = 8,
                            Description = "Ascension Day Eve",
                            IsDayBeforeHoliday = false,
                            Month = 5,
                            Year = 2013
                        },
                        new
                        {
                            Id = 8,
                            CityId = 1,
                            Day = 9,
                            Description = "Ascension Day",
                            IsDayBeforeHoliday = false,
                            Month = 5,
                            Year = 2013
                        },
                        new
                        {
                            Id = 9,
                            CityId = 1,
                            Day = 5,
                            Description = "National Day Eve",
                            IsDayBeforeHoliday = false,
                            Month = 6,
                            Year = 2013
                        },
                        new
                        {
                            Id = 10,
                            CityId = 1,
                            Day = 6,
                            Description = "National Day",
                            IsDayBeforeHoliday = false,
                            Month = 6,
                            Year = 2013
                        },
                        new
                        {
                            Id = 11,
                            CityId = 1,
                            Day = 21,
                            Description = "Midsummer Eve",
                            IsDayBeforeHoliday = false,
                            Month = 6,
                            Year = 2013
                        },
                        new
                        {
                            Id = 12,
                            CityId = 1,
                            Day = 1,
                            Description = "All Saints' Day",
                            IsDayBeforeHoliday = false,
                            Month = 11,
                            Year = 2013
                        },
                        new
                        {
                            Id = 13,
                            CityId = 1,
                            Day = 24,
                            Description = "Christmas Eve",
                            IsDayBeforeHoliday = false,
                            Month = 12,
                            Year = 2013
                        },
                        new
                        {
                            Id = 14,
                            CityId = 1,
                            Day = 25,
                            Description = "Christmas Day",
                            IsDayBeforeHoliday = false,
                            Month = 12,
                            Year = 2013
                        },
                        new
                        {
                            Id = 15,
                            CityId = 1,
                            Day = 26,
                            Description = "Boxing Day",
                            IsDayBeforeHoliday = false,
                            Month = 12,
                            Year = 2013
                        },
                        new
                        {
                            Id = 16,
                            CityId = 1,
                            Day = 31,
                            Description = "New Year's Eve",
                            IsDayBeforeHoliday = false,
                            Month = 12,
                            Year = 2013
                        },
                        new
                        {
                            Id = 17,
                            CityId = 1,
                            Day = 31,
                            Description = "Day before New Year",
                            IsDayBeforeHoliday = true,
                            Month = 12,
                            Year = 2012
                        },
                        new
                        {
                            Id = 18,
                            CityId = 1,
                            Day = 27,
                            Description = "Day before Maundy Thursday",
                            IsDayBeforeHoliday = true,
                            Month = 3,
                            Year = 2013
                        },
                        new
                        {
                            Id = 19,
                            CityId = 1,
                            Day = 31,
                            Description = "Day before Easter Monday",
                            IsDayBeforeHoliday = true,
                            Month = 3,
                            Year = 2013
                        },
                        new
                        {
                            Id = 20,
                            CityId = 1,
                            Day = 29,
                            Description = "Day before April 30",
                            IsDayBeforeHoliday = true,
                            Month = 4,
                            Year = 2013
                        },
                        new
                        {
                            Id = 21,
                            CityId = 1,
                            Day = 7,
                            Description = "Day before May 8",
                            IsDayBeforeHoliday = true,
                            Month = 5,
                            Year = 2013
                        },
                        new
                        {
                            Id = 22,
                            CityId = 1,
                            Day = 4,
                            Description = "Day before National Day Eve",
                            IsDayBeforeHoliday = true,
                            Month = 6,
                            Year = 2013
                        },
                        new
                        {
                            Id = 23,
                            CityId = 1,
                            Day = 20,
                            Description = "Day before Midsummer Eve",
                            IsDayBeforeHoliday = true,
                            Month = 6,
                            Year = 2013
                        },
                        new
                        {
                            Id = 24,
                            CityId = 1,
                            Day = 31,
                            Description = "Day before All Saints",
                            IsDayBeforeHoliday = true,
                            Month = 10,
                            Year = 2013
                        },
                        new
                        {
                            Id = 25,
                            CityId = 1,
                            Day = 23,
                            Description = "Day before Christmas Eve",
                            IsDayBeforeHoliday = true,
                            Month = 12,
                            Year = 2013
                        },
                        new
                        {
                            Id = 26,
                            CityId = 1,
                            Day = 30,
                            Description = "Day before New Year's Eve",
                            IsDayBeforeHoliday = true,
                            Month = 12,
                            Year = 2013
                        });
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollFeeSchedule", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", "City")
                        .WithMany("TollFeeSchedules")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.TollFreeDate", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Domain.Entities.City", "City")
                        .WithMany("TollFreeDates")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Domain.Entities.City", b =>
                {
                    b.Navigation("TollFeeSchedules");

                    b.Navigation("TollFreeDates");
                });
#pragma warning restore 612, 618
        }
    }
}
